name: Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true

jobs:
  secrets:
    name: secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment)] }}
    steps:
      - run: echo $environment
