name: Secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy to"
        required: true

jobs:
  secrets:
    name: secrets
    runs-on: ubuntu-latest
    env:
      SA: ${{ secrets[format('{0}_SA', inputs.SA)] }}
    steps:
      - run: echo "$SA"
