name: forecast

on:
  workflow_dispatch:
    inputs:
      project_id:
        required: true
        type: string
        description: Please input GCP Project ID
      servicekey:
        required: true
        type: string
        description: GCP service accout key file

jobs:
  # do_the_thing:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Mask Password
  #     run: |
  #       SA_KEY=$(jq -r '.inputs.servicekey' $GITHUB_EVENT_PATH)
  #       echo ::add-mask::$SA_KEY
  #       echo SA_KEY=$SA_KEY >> $GITHUB_ENV
  #   - name: Call API
  #     env:
  #       project_id: ${{ inputs.project_id }}
  #       service-json-key: ${{ inputs.servicekey }}
  #     run: |
  #       echo "$project_id"
  #       echo "$service-json-key"
  gcloud-auth:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Mask Password
      run: |
        SA_KEY=$(jq -r '.inputs.servicekey' $GITHUB_EVENT_PATH)
        echo ::add-mask::$SA_KEY
        echo SA_KEY=$SA_KEY >> $GITHUB_ENV

    - uses: 'actions/checkout@v4'

    - name: 'Google auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ env.SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'beta,config-connector,gke-gcloud-auth-plugin'
        
    - name: 'check gcloud'
      run: 'gcloud info'
      
    - name: 'Use gcloud CLI'
      env:
        project_id: ${{ inputs.project_id }}
      run: |
         # sudo apt-get install google-cloud-sdk-config-connector
         # gcloud components install config-connector
         # gcloud beta resource-config bulk-export --project=genial-current-395813 --resource-types=ComputeDisk > vms.tf
         # gcloud beta resource-config list-resource-types
         # gcloud beta resource-config bulk-export 
         gcloud components list
         gcloud config list project
         # gcloud services list --enabled
         # gcloud services list --enabled --project=genial-current-395813
         gcloud services enable cloudasset.googleapis.com
         gcloud beta resource-config list-resource-types
         gcloud beta resource-config bulk-export --project=genial-current-395813 --resource-types=ComputeDisk --resource-format=terraform >> disks.tf
         ls
         pwd
         
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
        # See https://github.com/infracost/actions/tree/master/setup for other inputs
        # If you can't use this action, see Docker images in https://infracost.io/cicd
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}  
        
    # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      run: |
        pwd
        ls
        infracost breakdown --path disks.tf  --format json --out-file infracost-base.json 
        cat infracost-base.json
        cat infracost-base.json | jq -r '.totalMonthlyCost'
   
