name: Secrets

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy to"
        required: true

jobs:
  secrets:
    name: secrets
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets[format('{0}_A', github.event.inputs.env)] }}
